version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        <% if (forestEmail) {%>- forestEmail=<%= forestEmail %><% } %>
        <% if (forestProjectName) {%>- forestProjectName=<%= forestProjectName %><% } %>
    container_name: <%= appName %>
    environment:
      - DATABASE_URL=<%= databaseUrl %>
      - AUTH_SECRET=<%= authSecret %>
      <% if (!port) {%># <% } %>- PORT=<%= port %>
      <% if (!ssl) {%># <% } %>- SSL_DATABASE=true
      <% if (!encrypt) {%># <% } %>- ENCRYPT_DATABASE=true
      <% if (dbSchema) {%>- DATABASE_SCHEMA=<%= dbSchema %><% } %>
    ports:
      - "<%= port %>:<%= port %>"
    volumes:
      - ./:/usr/src/app
